//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFApostar.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPFApostar.Resources.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro que desea cancelar la transacción?.
        /// </summary>
        internal static string CancelTransaction {
            get {
                return ResourceManager.GetString("CancelTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estableciendo comunicación....
        /// </summary>
        internal static string ComunicationServer {
            get {
                return ResourceManager.GetString("ComunicationServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡No se pudo establecer comunicación con el servidor!.
        /// </summary>
        internal static string ComunicationServerFail {
            get {
                return ResourceManager.GetString("ComunicationServerFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea  depositar la cantidad ingresada?.
        /// </summary>
        internal static string ConsignAmount {
            get {
                return ResourceManager.GetString("ConsignAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estamos consultando las coincidencias. Regálenos unos segundos.
        /// </summary>
        internal static string ConsultingConinsidences {
            get {
                return ResourceManager.GetString("ConsultingConinsidences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar {0}..
        /// </summary>
        internal static string EnterField {
            get {
                return ResourceManager.GetString("EnterField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el NIT de la empresa.
        /// </summary>
        internal static string EnterId {
            get {
                return ResourceManager.GetString("EnterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese los billetes y monedas que se indican a continuación en los dispositivos dispensador de billetes y dispensador de monedas.
        /// </summary>
        internal static string EnterMonyDispenser {
            get {
                return ResourceManager.GetString("EnterMonyDispenser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el nombre de la empresa.
        /// </summary>
        internal static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error! Por favor intentelo más tarde.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor seleccione los certificados que desea comprar.
        /// </summary>
        internal static string ErrorCertificate {
            get {
                return ResourceManager.GetString("ErrorCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error imprimiendo los certificados. se cancelara la transacción y devolverá el dinero ingresado.
        /// </summary>
        internal static string ErrorCertificatesPrint {
            get {
                return ResourceManager.GetString("ErrorCertificatesPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Señor usuario, no se encontraron coincidencias, vuelva a intentarlo.
        /// </summary>
        internal static string ErrorCoincidences {
            get {
                return ResourceManager.GetString("ErrorCoincidences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario y/o contraseña incorrectos.
        /// </summary>
        internal static string ErrorDates {
            get {
                return ResourceManager.GetString("ErrorDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En el momento no hay certificados para generar, vuelva pronto..
        /// </summary>
        internal static string ErrorFoundFiles {
            get {
                return ResourceManager.GetString("ErrorFoundFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar un nit válido..
        /// </summary>
        internal static string ErrorId {
            get {
                return ResourceManager.GetString("ErrorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar un nombre válido..
        /// </summary>
        internal static string ErrorName {
            get {
                return ResourceManager.GetString("ErrorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El dispositivo no puede imprimir el comprobante en este momento, desea continuar.
        /// </summary>
        internal static string ErrorNoPaper {
            get {
                return ResourceManager.GetString("ErrorNoPaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error en la devolución del dinero. Por favor comuniquese con un administrador..
        /// </summary>
        internal static string ErrorPayment {
            get {
                return ResourceManager.GetString("ErrorPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo completar la impresión de todos los certificatos. Por favor diríjase a las taquillas..
        /// </summary>
        internal static string ErrorPrintCertificate {
            get {
                return ResourceManager.GetString("ErrorPrintCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En este momento no se pueden imprimir certificados..
        /// </summary>
        internal static string ErrorPrinter {
            get {
                return ResourceManager.GetString("ErrorPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error con el servicio de Login.
        /// </summary>
        internal static string ErrorServiceLogin {
            get {
                return ResourceManager.GetString("ErrorServiceLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo crear la transacción. Por favor vuelve a intentarlo..
        /// </summary>
        internal static string ErrorTransaction {
            get {
                return ResourceManager.GetString("ErrorTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El codigo QR ingresado es inválido.
        /// </summary>
        internal static string ErrorValidaQr {
            get {
                return ResourceManager.GetString("ErrorValidaQr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Señor usuario estamos Finalizando la transacción. Espere un momento..
        /// </summary>
        internal static string FinishTransaction {
            get {
                return ResourceManager.GetString("FinishTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se entrego completamente el dinero.
        /// </summary>
        internal static string IncompleteMony {
            get {
                return ResourceManager.GetString("IncompleteMony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha ingresado información incorrecta, por favor validar la información y volver a intentarlo.
        /// </summary>
        internal static string InfoIncorrect {
            get {
                return ResourceManager.GetString("InfoIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El error se presentó al inicio del cajero.
        /// </summary>
        internal static string InformationError {
            get {
                return ResourceManager.GetString("InformationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validando información. Por favor espere..
        /// </summary>
        internal static string LoadInformation {
            get {
                return ResourceManager.GetString("LoadInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estamos contando su dinero, espere unos segundos.
        /// </summary>
        internal static string MessageReturnMony {
            get {
                return ResourceManager.GetString("MessageReturnMony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El kiosco entro en modo administrativo.
        /// </summary>
        internal static string ModoAdministrativo {
            get {
                return ResourceManager.GetString("ModoAdministrativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo continuar entregando el dineroç.
        /// </summary>
        internal static string NoContinue {
            get {
                return ResourceManager.GetString("NoContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede continuar con la transacción. Intentelo más tarde.
        /// </summary>
        internal static string NoContinueTransaction {
            get {
                return ResourceManager.GetString("NoContinueTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se logro iniciar el paypad.
        /// </summary>
        internal static string NoGoInitial {
            get {
                return ResourceManager.GetString("NoGoInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin información para mostrar.
        /// </summary>
        internal static string NoInformation {
            get {
                return ResourceManager.GetString("NoInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay datos para mostrar en estos momentos..
        /// </summary>
        internal static string NoInfoShow {
            get {
                return ResourceManager.GetString("NoInfoShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se logro insertar el pagador con id.
        /// </summary>
        internal static string NoInsertPayment {
            get {
                return ResourceManager.GetString("NoInsertPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se logro insertar la transacción.
        /// </summary>
        internal static string NoInsertTransaction {
            get {
                return ResourceManager.GetString("NoInsertTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El kiosco no cuenta con suficiente dinero para operar..
        /// </summary>
        internal static string NoMoneyKiosco {
            get {
                return ResourceManager.GetString("NoMoneyKiosco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede continuar con la transacción. por favor intentarlo mas tarde.
        /// </summary>
        internal static string NoProccessInformation {
            get {
                return ResourceManager.GetString("NoProccessInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El kiosco está temporalmente fuera de servicio.
        /// </summary>
        internal static string NoService {
            get {
                return ResourceManager.GetString("NoService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La transacción finalizó con novedad.
        /// </summary>
        internal static string NoveltyTransation {
            get {
                return ResourceManager.GetString("NoveltyTransation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El cajero está fuera de servicio en este momento, por favor intente más tarde.
        /// </summary>
        internal static string OutService {
            get {
                return ResourceManager.GetString("OutService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dispositivo entra en modo administrativo.
        /// </summary>
        internal static string PaypadGoAdmin {
            get {
                return ResourceManager.GetString("PaypadGoAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dispositivo inicia correctamente.
        /// </summary>
        internal static string PaypadStarSusses {
            get {
                return ResourceManager.GetString("PaypadStarSusses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de etiqueta negra.
        /// </summary>
        internal static string PrinterErrorTiketBlak {
            get {
                return ResourceManager.GetString("PrinterErrorTiketBlak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El papel se agotará.
        /// </summary>
        internal static string PrinterExhaustPapper {
            get {
                return ResourceManager.GetString("PrinterExhaustPapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay papel en la impresora.
        /// </summary>
        internal static string PrinterNoPapper {
            get {
                return ResourceManager.GetString("PrinterNoPapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sobrecalentamiento de cabezal de impresión.
        /// </summary>
        internal static string PrinterOverheatingHeader {
            get {
                return ResourceManager.GetString("PrinterOverheatingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La impresora y la biblioteca de llamadas no coinciden.
        /// </summary>
        internal static string PrintErrorLibrary {
            get {
                return ResourceManager.GetString("PrintErrorLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encabezado de impresión abierto.
        /// </summary>
        internal static string PrintHeaderOpen {
            get {
                return ResourceManager.GetString("PrintHeaderOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuerde siempre esperar la tirilla de soporte de su.
        /// </summary>
        internal static string PrintMs1 {
            get {
                return ResourceManager.GetString("PrintMs1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pago, es el único documento que lo respalda..
        /// </summary>
        internal static string PrintMs2 {
            get {
                return ResourceManager.GetString("PrintMs2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La impresora no está conectada o encendida.
        /// </summary>
        internal static string PrintNoConect {
            get {
                return ResourceManager.GetString("PrintNoConect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La impresora está normal.
        /// </summary>
        internal static string PrintNormal {
            get {
                return ResourceManager.GetString("PrintNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuchillo de corte no RESET.
        /// </summary>
        internal static string PrintReset {
            get {
                return ResourceManager.GetString("PrintReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Retire los billetes y monedas que se indican a continuación, en los dispositivos aceptador de billetes y aceptador de monedas.
        /// </summary>
        internal static string RemoveMonyAceptance {
            get {
                return ResourceManager.GetString("RemoveMonyAceptance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Retire los billetes y monedas que se indican a continuación de los dispositivos dispensador de billetes y dispensador de monedas.
        /// </summary>
        internal static string RemoveMonyDispenser {
            get {
                return ResourceManager.GetString("RemoveMonyDispenser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error a la hora de devolver el dinero.
        /// </summary>
        internal static string ReturnMoneyMs1 {
            get {
                return ResourceManager.GetString("ReturnMoneyMs1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor comuniquese con un administrador..
        /// </summary>
        internal static string ReturnMoneyMs2 {
            get {
                return ResourceManager.GetString("ReturnMoneyMs2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardando información. Por favor espere....
        /// </summary>
        internal static string SaveTransaction {
            get {
                return ResourceManager.GetString("SaveTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comprobando estado del PayPlus....
        /// </summary>
        internal static string StatePayPlus {
            get {
                return ResourceManager.GetString("StatePayPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡El dispositivo no cuenta con cargue suficiente!.
        /// </summary>
        internal static string StatePayPlusFail {
            get {
                return ResourceManager.GetString("StatePayPlusFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transacción exitosa.
        /// </summary>
        internal static string SussesTransaction {
            get {
                return ResourceManager.GetString("SussesTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transacción cancelada.
        /// </summary>
        internal static string TransactionCancel {
            get {
                return ResourceManager.GetString("TransactionCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La transacción ha finalizado correctamente..
        /// </summary>
        internal static string TransactionFinish {
            get {
                return ResourceManager.GetString("TransactionFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transacción finalizada correctamente.
        /// </summary>
        internal static string TransactionFinishSucces {
            get {
                return ResourceManager.GetString("TransactionFinishSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiene una actualizacion pendiente por favor no manipule ni apague el PayPlus mientras termina la instalacion..
        /// </summary>
        internal static string UpdateAplication {
            get {
                return ResourceManager.GetString("UpdateAplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validando periférico ....
        /// </summary>
        internal static string ValidatePeripherals {
            get {
                return ResourceManager.GetString("ValidatePeripherals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡No se lograrón iniciar los dispositivos!.
        /// </summary>
        internal static string ValidatePeripheralsFail {
            get {
                return ResourceManager.GetString("ValidatePeripheralsFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Espere mientras se configura el dispositivo para iniciar.
        /// </summary>
        internal static string WaitConfigurate {
            get {
                return ResourceManager.GetString("WaitConfigurate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El kiosco inicia correctamente.
        /// </summary>
        internal static string YesGoInitial {
            get {
                return ResourceManager.GetString("YesGoInitial", resourceCulture);
            }
        }
    }
}
